name: CI Client

on:
  push:
    paths:
      - 'grpc-client/**'
    branches: [main]
  pull_request:
    paths:
      - 'grpc-client/**'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release --manifest-path grpc-client/Cargo.toml

      - name: Run tests
        run: cargo test --release --manifest-path grpc-client/Cargo.toml
