name: CI Server

on:
  push:
    paths:
      - 'grpc-server/**'
    branches: [main]
  pull_request:
    paths:
      - 'grpc-server/**'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build
        run: cargo build --release --manifest-path grpc-server/Cargo.toml

      - name: Run tests
        run: cargo test --release --manifest-path grpc-server/Cargo.toml
